server:
  port: 80
eureka:
  client:          # 客户端进行 eureka 注册配置
    service-url:
      defaultZone: http://ninja:ninja650@eureka-7001.com:7001/eureka, http://ninja:ninja650@eureka-7002.com:7002/eureka, http://ninja:ninja650@eureka-7003.com:7003/eureka
    register-with-eureka: false   #不注册到eureka