spring:
  profiles:
    active: dev-7001
---
server:
  port: 7001
eureka:
  instance:                                  # eureka实例定义
    hostname: eureka-7001.com
  #    lease-renewal-interval-in-seconds: 2     # 心跳时间间隔 (默认是30秒)
#    lease-expiration-duration-in-seconds: 5  # 上一次心跳等待下一次心跳的间隔时间,超过此时间认为宕机 (默认是90秒)
  client:                                    # 客户端进行eureka注册的配置
    register-with-eureka: false              # 当前服务不注册到eureka中
    fetch-registry: false                    # 不通过eureka获取注册信息
    service-url:
      defaultZone: http://ninja:ninja650@eureka-7002.com:7002/eureka,http://ninja:ninja650@eureka-7003.com:7003/eureka
#  server:
#    eviction-interval-timer-in-ms: 60000  # 设置清理的间隔时间 单位:毫秒 (默认是60秒)
#    enable-self-preservation: false       # 关闭保护模式 不建议
spring:
  profiles: dev-7001
  application:
    name: microcloud-eureka-7001
  security:
    user:
      name: ninja
      password: ninja650
#  security:
#    user:
#      name: hello
#      password: eureka
#################### 7002 #####################
---
server:
  port: 7002
eureka:
  instance:                                  # eureka实例定义
    hostname: eureka-7002.com
  client:                                    # 客户端进行eureka注册的配置
    register-with-eureka: false              # 当前服务不注册到eureka中
    fetch-registry: false                    # 不通过eureka获取注册信息
    service-url:
      defaultZone: http://ninja:ninja650@eureka-7001.com:7001/eureka,http://ninja:ninja650@eureka-7003.com:7003/eureka
spring:
  profiles: dev-7002
  application:
    name: microcloud-eureka-7002
  security:
    user:
      name: ninja
      password: ninja650

#################### 7003 #####################
---
server:
  port: 7003
eureka:
  instance:                                  # eureka实例定义
    hostname: eureka-7003.com
  client:                                    # 客户端进行eureka注册的配置
    register-with-eureka: false              # 当前服务不注册到eureka中
    fetch-registry: false                    # 不通过eureka获取注册信息
    service-url:
      defaultZone: http://ninja:ninja650@eureka-7001.com:7001/eureka,http://ninja:ninja650@eureka-7002.com:7002/eureka
spring:
  profiles: dev-7003
  application:
    name: microcloud-eureka-7003
  security:
    user:
      name: ninja
      password: ninja650